./soc.v
./tb_soc.v
./core/core.v
./core/datapath/stages/stage_decode.v
./core/datapath/stages/stage_execute.v
./core/datapath/stages/stage_fetch.v
./core/datapath/stages/stage_write_back.v
./core/datapath/pipeline_regs/ex_mem.v
./core/datapath/pipeline_regs/id_ex.v
./core/datapath/pipeline_regs/if_id.v
./core/datapath/pipeline_regs/mem_wb.v
./core/datapath/units/alu.v
./core/datapath/units/extend_unit.v
./core/datapath/units/hazard_unit.v
./core/datapath/units/load_extend.v
./core/datapath/units/register_file.v
./core/datapath/units/store_align.v
./core/datapath/components/adder.v
./core/datapath/components/full_adder.v
./core/datapath/components/mux_2x1.v
./core/datapath/components/mux_3x1.v
./core/datapath/components/mux_4x1.v
./core/datapath/components/next_pc.v
./core/datapath/components/pc_target.v
./core/datapath/datapath.v
./core/control_unit/control_unit.v
./core/control_unit/op_decoder.v
./core/control_unit/alu_decoder.v
./memory/dual_port_memory.v
